[package]
name = "bank"
publish = false

edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
unis.workspace = true

uuid.workspace = true
bincode.workspace = true
validator.workspace = true
