[package]
name = "examples"
version = "0.0.0"
publish = false

edition.workspace = true

[dev-dependencies]
unis.workspace = true

uuid.workspace = true
tracing.workspace = true
validator.workspace = true
serde.workspace = true
bincode.workspace = true
