name = "bank"
hostname = ""
bootstrap = "localhost:30001,localhost:30002,localhost:30003"

[subscriber.Note]
hotspot = true
sems = 300

[sender.Note]
sems = 50

[cc.Note]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"

[tc.Note]
"auto.offset.reset" = "earliest"
"auto.commit.interval.ms" = "1000"

[tp]
"linger.ms" = "1"

[cp]
"linger.ms" = "1"
