bootstrap = "localhost:30001,localhost:30002,localhost:30003"
hostname = ""

[subscriber.Note]
hotspot = true
sems = 300

[sender.Note]
sems = 50

[cc.Note]
"session.timeout.ms" = "6000"
"enable.auto.commit" = "false"
"auto.offset.reset" = "latest"
"fetch.message.max.bytes" = "10485760"
"queued.min.messages" = "1000"

[tp]
"linger.ms" = "1"

[cp]
"linger.ms" = "1"
