[package]
name = "unis-kafka"
description = "unis框架的Kafka实现。"

version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
rdkafka = "0.38"

unis.workspace = true
unis-macros.workspace = true

uuid.workspace = true
ahash.workspace = true
crossbeam.workspace = true
bincode.workspace = true
bytes.workspace = true
tokio.workspace = true
futures.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true

config.workspace = true

[dev-dependencies]
domain = { path = "../domain" }
unis-test = { path = "../unis-test" }
home.workspace = true
rstest.workspace = true
